backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: settings
    label: Settings
    files: 
      - name: config
        label: Configuration
        file: site-meta-data.json
        fields:
          - label: Site Title
            name: title
            widget: string
            required: true
          - label: Description
            name: description
            widget: string
          - label: headerimage
            name: Header Image
            widget: image
          - label: Wedding Details
            name: details
            widget: object
            fields: 
              - {label: "Date & Time", name: datetime, widget: datetime, default: "", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", format: "LLL", pickerUtc: true}
              - {label: State, name: state, widget: string}
              - {label: City, name: city, widget: string}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Image, name: image, widget: image}